/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "background": "#FAFAFA",
        "surface": "#FFFFFF",
        "surface-secondary": "#F7F7F8",
        "hover": "#F4F4F5",
        "border-color": "#E4E4E7",
        "strong-border": "#D4D4D8",
        "primary-text": "#18181B",
        "secondary-text": "#52525B",
        "muted-text": "#71717A",
        "primary": "#4F46E5",
        "primary-hover": "#4338CA",
        "light-accent": "#EEF2FF",

        // Compatibility mappings for legacy design tokens
        "surface-dim": "#F4F4F5",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#FAFAFA",
        "surface-container": "#F7F7F8",
        "surface-container-high": "#F4F4F5",
        "surface-container-highest": "#E4E4E7",
        "on-surface": "#18181B",
        "on-surface-variant": "#52525B",
        "inverse-surface": "#18181B",
        "inverse-on-surface": "#FAFAFA",
        "outline": "#71717A",
        "outline-variant": "#E4E4E7",
        "surface-tint": "#4F46E5",
        "on-primary": "#FFFFFF",
        "primary-container": "#4F46E5",
        "on-primary-container": "#EEF2FF",
        "inverse-primary": "#818CF8",
        "secondary": "#52525B",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#F4F4F5",
        "on-secondary-container": "#18181B",
        "tertiary": "#D97706",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#FEF3C7",
        "on-tertiary-container": "#92400E",
        "error": "#DC2626",
        "on-error": "#FFFFFF",
        "error-container": "#FEE2E2",
        "on-error-container": "#991B1B",
        "surface-variant": "#F4F4F5"
      },
      boxShadow: {
        'modal': '0 8px 24px rgba(0, 0, 0, 0.08)',
        'dropdown': '0 8px 24px rgba(0, 0, 0, 0.08)',
        'card': '0 1px 2px rgba(0, 0, 0, 0.04)',
      },
      borderRadius: {
        "sm": "4px",
        "DEFAULT": "6px",
        "md": "6px",
        "lg": "8px",
        "xl": "10px",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "display": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "h1": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "h2": ["18px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
